<div class="row animated fadeInDown">
    <div class="col-lg-12">
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Project</th>
                            <th>Health</th>
                            <th>Last Success</th>
                            <th>Last Failure</th>
                            <th>Success/Failures</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php if ($this->project_result): ?>
                            <?php foreach ($this->project_result as $project): ?>
                                <tr class="bg-danger  pointer" onclick="go('<?php echo $this->url('project/view',array('id'=>$project->id))?>');">
                                    <td><i title=" <?php echo $project->type; ?>"
                                           class="fa fa-bitbucket text-primary"></i></td>

                                    <td>
                                        <?php echo $project->header; ?>
                                    </td>
                                    <td><span class="label label-danger">Bad</span></td>
                                    <td><?php echo $project->header; ?></td>
                                    <td><?php echo $project->header; ?></td>
                                    <td>
                                        <img alt="failed"
                                             src="http://phpci.icqparty.ru/assets/img/icon-build-failed.png"><img
                                            alt="failed"
                                            src="http://phpci.icqparty.ru/assets/img/icon-build-failed.png"><img
                                            alt="ok" src="http://phpci.icqparty.ru/assets/img/icon-build-ok.png"><img
                                            alt="failed"
                                            src="http://phpci.icqparty.ru/assets/img/icon-build-failed.png"><img
                                            alt="failed"
                                            src="http://phpci.icqparty.ru/assets/img/icon-build-failed.png"></td>

                                </tr>
                            <?php endforeach ?>
                        <?php endif ?>
                        </tbody>
                    </table>

        </div>
    </div>
</div>