<?php if ($this->pageCount > 1): ?>

    <ul class="pagination pagination-sm">
        <?php if (isset($this->previous)): ?>
            <li class="previous"><a
                    href="<?php echo $this->url($this->route, array('page' => $this->previous),array('query'=>$this->params)); ?><?php echo $param ?>"
                    title=""> <i class="fa fa-chevron-left"> </i></a></li>
        <?php endif; ?>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php $active = ''; ?>
            <?php if ($page == $this->current): ?>
                <?php $active = 'class="active"'; ?>
            <?php endif; ?>
            <li <?php echo $active; ?> ><a
                    href="<?php echo $this->url($this->route, array('page' => $page),array('query'=>$this->params)); ?><?php echo $page ?>"
                    title="На страницу <?php echo $page?>"><?php echo $page; ?></a></li>
        <?php endforeach; ?>
        <?php if (isset($this->next)): ?>
            <li class="next"><a
                    href="<?php echo $this->url($this->route, array('page' => $this->next),array('query'=>$this->params)); ?><?php echo $page ?>"
                    title="Следующая страница"> <i class="fa fa-chevron-right"></i> </a></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>