<div class="row">
    <div class="col-lg-12 text-center">
        <img src="https://travis-ci.org/icqparty/linebuild.svg?branch=master">
        <a href='https://coveralls.io/r/icqparty/linebuild?branch=dev-master'><img
                src='https://coveralls.io/repos/icqparty/linebuild/badge.png?branch=master'
                alt='Coverage Status master'/></a>
        <a href='https://coveralls.io/r/icqparty/linebuild?branch=dev-master'><img
                src='https://coveralls.io/repos/icqparty/linebuild/badge.png?branch=dev-master'
                alt='Coverage Status dev'/></a>

    </div>
</div>
