<div class="clearfix"></div>
<footer id="footer">
    <div class="text-center clearfix">
        <p>
            <small>&copy myxdashboard 2014, Admin dashboard framework base on bootstrap</small>
            <br/><br/>
            <a href="#" class="btn btn-xs btn-circle btn-twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="btn btn-xs btn-circle btn-facebook"><i class="fa fa-facebook"></i></a>
            <a href="#" class="btn btn-xs btn-circle btn-gplus"><i class="fa fa-google-plus"></i></a>
        </p>
    </div>
</footer>