<div class="navbar navbar-default navbar-fixed-top">
    <button class="navbar-toggle" type="button" data-toggle="collapse" id="menu-toggler">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" href="<?php echo $this->url('home')?>"><i class="fa fa-cogs"></i> <b>LINE</b>BUILD</a>

        <div class="navbar-collapse collapse" style="margin-right: 25px;">
            <ul class="nav navbar-nav navbar-right" >

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img class="pull-left" style="margin-right: 7px; margin-top: -5px; border-radius: 50%" src="//www.gravatar.com/avatar/0647cfa602aea5eb420eb94d334fb0a5?d=mm&amp;s=30">

                        <strong>icqparty</strong><b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu  animated fadeInRight" role="menu">
                        <li><a href="<?php echo $this->url('user/profile')?>">Edit Profile</a></li>
                        <li class="divider"></li>
                        <li><a href="<?php echo $this->url('user/logout')?>">Log out</a></li>
                    </ul>
                </li>


            </ul>
        </div>

</div>