<div id="sidebar-nav">
    <div class="profile-hidder">
        <ul class="nav">
            <li class="nav-profile">
                <div class="image">
                    <a href="<?php echo $this->url('user/profile');?>">
                        <img src="http://www.gravatar.com/avatar/0647cfa602aea5eb420eb94d334fb0a5?d=mm&s=25" alt="">
                    </a>
                </div>
                <div class="info">

                    <a href="#">icqparty <b class="caret"></b></a>
                    <small>UX-UI Designer</small>

                </div>
            </li>
        </ul>
    </div>

    <ul id="dashboard-menu">
        <li>

            <a href="<?php echo $this->url('home')?>">
                <i class="fa fa-laptop"></i>
                Dashboard
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url('project')?>">
                <i class="fa fa-th-list"></i>
                Projects
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url('project/add')?>">
                <i class="fa fa-plus"></i>
                Add Project
            </a>
        </li>

        <li>
            <a href="<?php echo $this->url('user')?>">
                <i class="fa fa-users"></i>
                Users
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url('user/profile')?>">
                <i class="fa fa-user"></i>
                Profile Settings
            </a>
        </li>
        <li>
            <a href="<?php echo $this->url('setting')?>">
                <i class="fa fa-cogs "></i>
                System Settings
            </a>
        </li>


    </ul>
</div>