<div id="wrap">

<div class="container dashboard">

<div class="wrapper-dashboard">

<div class="row">

<div class="col-md-3">

    <div class="profile-categories">

        <span>500+ connections</span>
        <ul class="clearfix">
            <li><img href="/assets/theme/default/image/profile-c-01.png" alt=""/></li>
            <li><img href="/assets/theme/default/image/profile-c-02.png" alt=""/></li>
            <li><img href="/assets/theme/default/image/profile-c-03.png" alt=""/></li>
            <li><img href="/assets/theme/default/image/profile-c-04.png" alt=""/></li>
            <li>
                <a href="index.html#">
                    <i class="fa fa-user"></i>
                </a>
            </li>
        </ul>
        <div class="hr"></div>

        <div class="wrap">
            <div class="view clearfix">
                <span class="title pull-left">page views</span>
                <span class="text pull-right first">1,595</span>
            </div>
            <div class="fav clearfix">
                <span class="title pull-left">favourited</span>
                <span class="text pull-right">120</span>
            </div>
            <div class="com clearfix">
                <span class="title pull-left">comments</span>
                <span class="text pull-right">34</span>
            </div>
        </div>

    </div>

    <div class="panel-style space custom-menu no-pad-r m-bot-30 m-top-30">

        <span class="grey-title">CUSTOM MENU</span>

        <ul>
            <li><a href="index.html#" class="tasks">Tasks <span></span></a></li>
            <li><a href="index.html#" class="timeline">Timeline <span></span></a></li>
            <li><a href="index.html#" class="calendar">Calendar <span></span></a></li>
            <li><a href="index.html#" class="connections">Connections <span></span></a></li>
        </ul>

        <div class="latest-uploads">
            <span class="grey-title">LATEST UPLOADS</span>

            <ul>
                <li><a href="index.html#" class="doc">Documentation.pdf<span></span></a></li>
                <li><a href="index.html#" class="home">Rentacar-Homepage.png<span></span></a></li>
                <li><a href="index.html#" class="mobile">Mobile-Description.pdf<span></span></a></li>
            </ul>

            <a href="index.html#" class="section-new">Add new section</a>

        </div>

    </div>

    <div class="share-block">
        <div class="top">
            <h3>Thanks for taking our survey!</h3>
            <span>Please share it</span>
        </div>
        <div class="bottom clearfix">
            <a href="index.html#" class="facebook">226</a>
            <a href="index.html#" class="twitter">97</a>
            <a href="index.html#" class="pinterest">163</a>
        </div>
    </div>


</div>

<div class="col-md-9">

<div class="white-panel-widget clearfix m-sidebar m-bot-30 no-pad">
    <div class="average-statistics-wrapper row no-margin">
        <h3>Average page statistics</h3>

        <div class="btn-group user-drop button-dropdown">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">

            </button>
            <ul class="dropdown-menu blue extra-s" role="menu">
                <li>
                    <a href="index.html#">Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a class="text" href="index.html#"> Remove </a>
                    <a class="icon" href="index.html#">
                        <i class="fa fa-plus"></i>
                    </a>
                </li>
                <li>
                    <a class="text" href="index.html#"> Minimize </a>
                    <a class="icon" href="index.html#">
                        <i class="fa fa-minus"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <!--<div id="myfirstchart" style="height: 250px;"></div>-->


    <div class="wrapper-circle-charts">

        <div class="wrp row no-margin">

            <div class="chart" data-percent="75" data-barColor="#3498DB" data-lineCap="butt" data-lineWidth="12"
                 data-trackColor="#C2E0F4" data-size="150">
                <span class="percent"></span>

                <p>CPU Usage</p>
            </div>


            <div class="chart green" data-percent="52" data-barColor="#2ABC68" data-lineCap="butt" data-lineWidth="12"
                 data-trackColor="#BFEBD1" data-size="150">
                <span class="percent"></span>

                <p>Server load</p>
            </div>


            <div class="chart green" data-percent="52" data-barColor="#2ABC68" data-lineCap="butt" data-lineWidth="12"
                 data-trackColor="#BFEBD1" data-size="150">
                <span class="percent"></span>

                <p>Server load</p>
            </div>


            <div class="chart red" data-percent="88" data-barColor="#E64D5F" data-lineCap="butt" data-lineWidth="12"
                 data-trackColor="#fff" data-size="150">
                <span class="percent"></span>

                <p>Server load</p>
            </div>


            <div class="chart green" data-percent="52" data-barColor="#2ABC68" data-lineCap="butt" data-lineWidth="12"
                 data-trackColor="#BFEBD1" data-size="150">
                <span class="percent"></span>

                <p>Server load</p>
            </div>

        </div>

    </div>

</div>

<div class="row">
<div class="col-md-7">

<div class="timeline-wrapper dash">

<div class="timeline-post">
    <ul>
        <li class="active"><a href="index.html#">Message</a></li>
        <li><a href="index.html#">Task</a></li>
        <li><a href="index.html#">Note</a></li>
    </ul>

    <input type="text" placeholder="Say something..." class="text"/>

    <div class="options clearfix">
        <ul>
            <li><a class="one" href="index.html#"></a></li>
            <li><a class="two" href="index.html#"></a></li>
            <li><a class="three" href="index.html#"></a></li>
            <li><a class="four" href="index.html#"></a></li>
        </ul>
        <a href="index.html#">Okay, post!</a>
    </div>
</div>

<div class="timeline-item">
    <div class="comment more-pad panel-style more">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-01.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">Dawid Owsianka</a> has added 16 new tasks to the <a
                href="index.html#">&ldquo;Dashboard&rdquo;</a> project.</p>
        <span>36 minutes ago &bull;<a href="index.html#"> 2 comments</a></span>

        <div class="more">
            <a data-related="455" href="index.html#">+ 3 more</a>
        </div>
    </div>
</div>

<div class="timeline-item preloaded" data-related="455">
    <div class="comment panel-style">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-03.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">John Smith</a> has added 10 new tasks to the <a href="index.html#">&ldquo;That
                nice&rdquo;</a> project.</p>
        <span>12 minutes ago &bull;<a href="index.html#"> 1 comment</a></span>
    </div>
</div>

<div class="timeline-item preloaded" data-related="455">
    <div class="comment panel-style">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-02.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">Michael Pitt</a> has added 11 new tasks to the <a
                href="index.html#">&ldquo;Great&rdquo;</a> project.</p>
        <span>16 minutes ago &bull;<a href="index.html#"> 2 comments</a></span>
    </div>
</div>

<div class="timeline-item preloaded" data-related="455">
    <div class="comment panel-style">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-04.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">Paul Scott</a> has added 9 new tasks to the <a href="index.html#">&ldquo;New&rdquo;</a>
            project.</p>
        <span>3 minutes ago &bull;<a href="index.html#"> 8 comments</a></span>
    </div>
</div>

<div class="timeline-item">
    <div class="comment more-pad image panel-style more image-section">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-02.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">Holly Ashworth</a> has added 16 new tasks to the <a href="index.html#">&ldquo;Healthy
                App&rdquo;</a> project.</p>
        <span>56 minutes ago</span>

        <div class="block-image">
            <img href="/assets/theme/default/image/post-img-01.jpg" alt=""/>

            <div class="info">
                <span>for purple magazine</span>

                <h2>Terry Richardson</h2>
            </div>
        </div>

        <div class="more">
            <a href="index.html#">+ 7 more</a>
        </div>
    </div>
</div>

<div class="timeline-item no-border">
    <div class="comment panel-style extra">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-03.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">Gary Hamilton</a> added new skills on his profile.</p>
        <span>1 hour ago &bull;<a href="index.html#"> 15 comments</a></span>
    </div>

    <div class="response">
        <div class="comment panel-style reply-pad">
            <div class="photo first">
                <img href="/assets/theme/default/image/post-small-01.png" alt=""/>
            </div>
            <div class="pin"></div>

            <a href="index.html#">Asmira Para&scaron;</a>
            <span>&minus; 15 minutes ago</span>

            <p>Rocky teams up with crazy photographer <strong>Terry Richardson</strong> to show the world why he&apos;s
                a <i>Fashion Killa.</i> For more <a href="index.html#">here</a>.</p>

            <div class="reply">
                <span>reply to<a href="index.html#"> @Mieszko DUDEK</a></span>
            </div>
        </div>
    </div>

    <div class="response">
        <div class="comment reply-pad panel-style">
            <div class="photo">
                <img href="/assets/theme/default/image/post-small-02.png" alt=""/>
            </div>
            <div class="pin"></div>

            <a href="index.html#">mieszko dudek</a>
            <span>&minus; 12 minutes ago</span>

            <p>I think I&apos;ll miss The Californians. Did it get repetitive at the end? Yeah. Did it peeve off east
                coasters who didn&apos;t get it? Yep.</p>

            <div class="reply">
                <span>reply to<a href="index.html#"> @Mieszko DUDEK</a></span>
            </div>
        </div>
    </div>

    <div class="response last">
        <div class="comment panel-style reply-pad">
            <div class="photo">
                <img href="/assets/theme/default/image/post-small-03.png" alt=""/>
            </div>
            <div class="pin"></div>

            <a href="index.html#">Angelika Maurer</a>
            <span>&minus; 5 minutes ago</span>

            <p><a href="index.html#" class="grey">@Terry Richardson</a> but they all can&apos;t be 100% drunk all the
                time. <br/><br/>Challenge accepted! :-)</p>

            <div class="reply">
                <span>reply to<a href="index.html#"> @Mieszko DUDEK</a></span>
            </div>
        </div>
        <span class="last"></span>
    </div>
</div>

<div class="timeline-comment">
    <div class="all-comments clearfix">
        <a class="com" href="index.html#">See all comments</a>
        <a class="bullets" href="index.html#"></a>
    </div>

    <div class="field-com">
        <div class="photo">
            <img href="/assets/theme/default/image/post-small-04.png" alt=""/>
        </div>
        <input type="text" placeholder="Add a comment..."/>
        <span class="nr">1</span>
        <span class="pin"></span>
    </div>
</div>

<div class="timeline-item">
    <div class="comment more-pad panel-style more">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-04.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">John Doe</a> is now connected to <a href="index.html#">John Smith</a>.</p>

        <p><a href="index.html#">Fergus Anderson</a> and 6 other people.</p>
        <span>2 days ago &bull;<a href="index.html#"> see the list</a></span>

        <div class="more">
            <a href="index.html#">+ 5 more</a>
        </div>
    </div>
</div>

<div class="timeline-item no-border">
    <div class="comment more-pad panel-style more">
        <div class="photo">
            <img href="/assets/theme/default/image/post-large-06.png" alt=""/>
        </div>
        <div class="pin"></div>

        <p><a href="index.html#">Angelina Smith</a> has added 3 new tasks to the <a href="index.html#">&ldquo;Nice
                Weather App&rdquo;</a>.</p>
        <span>1 week ago &bull;<a href="index.html#"> 10 comments</a></span>

        <div class="more">
            <a href="index.html#">+ 3 more</a>
        </div>
    </div>
</div>

</div>

</div>

<div class="col-md-5">

    <div class="widget-wrapper">
        <div class="panel-widget">
            <span>Note's Categories</span>

            <div class="btn-group user-drop button-dropdown">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">

                </button>
                <ul class="dropdown-menu blue" role="menu">
                    <li>
                        <a href="index.html#">Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text" href="index.html#"> Remove </a>
                        <a class="icon" href="index.html#">
                            <i class="fa fa-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a class="text" href="index.html#"> Minimize </a>
                        <a class="icon" href="index.html#">
                            <i class="fa fa-minus"></i>
                        </a>
                    </li>
                </ul>
            </div>

        </div>
        <div class="content extra">
            <ul class="notes-categories clearfix">

                <li><a href="index.html#">User Centered Design</a></li>
                <li><a href="index.html#">UI/UX</a></li>
                <li><a href="index.html#">Backend</a></li>
                <li><a href="index.html#">Creative direction</a></li>
                <li><a href="index.html#">Responsive</a></li>
                <li><a href="index.html#">Wordpress</a></li>
                <li><a href="index.html#">Java Development</a></li>
            </ul>
        </div>

    </div>

    <div class="widget-wrapper">
        <div class="panel-widget">
            <span>Tasks</span>

            <div class="btn-group user-drop button-dropdown">
                <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">

                </button>
                <ul class="dropdown-menu blue" role="menu">
                    <li>
                        <a href="index.html#">Settings</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a class="text" href="index.html#"> Remove </a>
                        <a class="icon" href="index.html#">
                            <i class="fa fa-plus"></i>
                        </a>
                    </li>
                    <li>
                        <a class="text" href="index.html#"> Minimize </a>
                        <a class="icon" href="index.html#">
                            <i class="fa fa-minus"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content">
            <ul class="task-feature">
                <li class="clearfix">
                    <div><input class="prettycheckbox" type="checkbox"/></div>
                    <span>Create clean and strong</span>
                </li>
                <li class="clearfix">
                    <div><input class="prettycheckbox" type="checkbox"/></div>
                    <span>Improve something on it</span>
                </li>
                <li class="clearfix">
                    <div><input class="prettycheckbox" type="checkbox"/></div>
                    <span>Backend CMS Admin panel</span>
                </li>
                <li class="clearfix">
                    <div><input class="prettycheckbox" type="checkbox"/></div>
                    <span>Small and useful set</span>
                </li>
                <li class="last-b clearfix">
                    <div><input class="prettycheckbox" type="checkbox"/></div>
                    <span>Prepare brand book</span>
                </li>
            </ul>
        </div>
    </div>

    <div id="messages-wrapper" class="m-top-30">
        <div class="m-sidebar row">
            <div class="m-sidebar-wrapper no-margin">
                <div class="row">
                    <h3>Messages</h3>

                    <div class="btn-group user-drop button-dropdown">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">

                        </button>
                        <ul class="dropdown-menu blue extra-s" role="menu">
                            <li>
                                <a href="index.html#">Settings</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a class="text" href="index.html#"> Remove </a>
                                <a class="icon" href="index.html#">
                                    <i class="fa fa-plus"></i>
                                </a>
                            </li>
                            <li>
                                <a class="text" href="index.html#"> Minimize </a>
                                <a class="icon" href="index.html#">
                                    <i class="fa fa-minus"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <ul class="wrapper-items">
                <li>
                    <img href="/assets/theme/default/image/messages-small-01.png" alt=""/>

                    <h3>Mike Tomson<span>now</span></h3>

                    <p>Lorem ipsum dolor sitamet, temporibitus harlem..</p>

                    <div class="bar"></div>
                </li>
                <li>
                    <img href="/assets/theme/default/image/messages-small-02.png" alt=""/>

                    <h3>John Lennon<span>today</span></h3>

                    <p>Born in the crime-infested Harlem neighberhood...</p>

                    <div class="bar"></div>
                </li>
                <li>
                    <img href="/assets/theme/default/image/messages-small-03.png" alt=""/>

                    <h3>Mary Jane<span>nov 12</span></h3>

                    <p>It could be done ;)</p>

                    <div class="bar"></div>
                </li>
                <li>
                    <img href="/assets/theme/default/image/messages-small-04.png" alt=""/>

                    <h3>Mark Twain<span>nov 12</span></h3>

                    <p>Rocky assembled this shit curabitur seemingly!</p>

                    <div class="bar"></div>
                </li>
                <li>
                    <img href="/assets/theme/default/image/messages-small-05.png" alt=""/>

                    <h3>Aaron Paul<span>nov 2</span></h3>

                    <p>I hope so, mate.</p>

                    <div class="bar"></div>
                </li>
            </ul>

            <div class="messages-link">
                <a href="http://nicolaegabriel.info/live/admin-easy-bootstrap/messages.html">See all messages</a>
            </div>
        </div>
    </div>

</div>
</div>


</div>

</div>

</div>

</div>

</div>